name: insulithiumtest
favicon: null
layout_spectrum: 0.11137381149455905
typography_spectrum: 0.9362426334992051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#676360'
    - '#bdaca4'
    - '#423d3a'
    - '#250d09'
  brandStrength: 0.32100707734934986
  lightness: 0.8721711062826216
  saturation: 0.16674054670147598
  rhythmicContrast: 0.43212766014039516
purpose: []
